import { createClient } from 'npm:@supabase/supabase-js'
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}})
const HRADY='https://www.hrady-zriceniny.cz/'
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-hradnik-geocode-key,x-hradnik-sync-key','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'}
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:CORS})
function clean(v:unknown){return String(v??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function norm(v=''){return clean(v).toLocaleLowerCase('cs-CZ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—−]/g,'-').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function slug(v=''){return norm(v).replace(/\s+/g,'_')}
function variants(name=''){const n=norm(name);const a=[n];if(n.includes(' - ')){for(const p of n.split(' - '))a.push(p.trim())}if(n.includes(' u '))a.push(n.split(' u ')[0].trim());return [...new Set(a.filter(x=>x.length>=4))]}
async function get(url:string,ms=16000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{'User-Agent':'Hradnik/1.0 (+https://hradnik.vercel.app)','Accept':'text/html,application/json;q=0.9,*/*;q=0.8'},signal:c.signal});if(!r.ok)return null;return await r.text()}catch{return null}finally{clearTimeout(t)}}
function gpsFrom(html:string){const t=clean(html);const m=t.match(/GPS:[\s\S]{0,700}?\|\s*(-?\d{1,3}(?:\.\d+)?)\s*,\s*(-?\d{1,3}(?:\.\d+)?)/i);if(!m)return null;const lat=Number(m[1]),lon=Number(m[2]);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<48||lat>52||lon<11||lon>20)return null;return{latitude:lat,longitude:lon}}
function header(html:string){const t=clean(html).slice(0,1400);return{district:t.match(/Okres:\s*([^\n]{2,100})/i)?.[1]?.trim()||'',text:t}}
function prefixes(kind:string){const k=norm(kind);if(k.includes('zricen'))return['zricenina','hrad','zamek','tvrz'];if(k.includes('zamek'))return['zamek','hrad','tvrz'];if(k.includes('tvrz'))return['tvrz','hrad','zamek'];if(k.includes('klaster'))return['klaster','komenda','hrad','zamek'];return['hrad','zricenina','zamek','tvrz','objekt']}
async function findHrady(p:any){const urls:string[]=[];const add=(u:string)=>{if(u&&!urls.includes(u))urls.push(u)};if(p.source_url&&/hrady-zriceniny\.cz\//i.test(p.source_url)&&!/seznam_komplet/i.test(p.source_url))add(p.source_url);for(const v of variants(p.name))for(const pre of prefixes(p.kind||''))add(`${HRADY}${pre}_${slug(v)}.htm`);for(const url of urls.slice(0,18)){const h=await get(url);if(!h)continue;const id=header(h),name=norm(p.name),base=variants(p.name)[1]||name,lead=norm(id.text),district=norm(p.district||'');if(!(lead.includes(name)||lead.includes(base)))continue;if(district&&id.district&&norm(id.district)!==district&&!norm(id.district).includes(district)&&!district.includes(norm(id.district)))continue;const gps=gpsFrom(h);if(gps)return{...gps,source:'Hrady-zříceniny.cz',source_url:url,confidence:.995}}return null}
function score(p:any,r:any,e:any){const label=norm(r?.label||e?.labels?.cs?.value||''),wanted=norm(p.name),desc=norm(e?.descriptions?.cs?.value||e?.descriptions?.en?.value||'');let s=0;if(label===wanted)s=100;else if(label&&wanted.includes(label))s=82;else if(label&&label.includes(wanted))s=82;for(const v of variants(p.name))if(v.length>4&&label===v)s=Math.max(s,90);if(/hrad|zamek|zricen|tvrz|pevnost|hradisko|palac|castle|ruin|fort|manor/i.test(label+' '+desc))s+=16;return Math.min(s,100)}
async function wikidataOne(p:any){try{const q=[p.name,p.district].filter(Boolean).join(' '),h=await get('https://www.wikidata.org/w/api.php?action=wbsearchentities&search='+encodeURIComponent(q)+'&language=cs&uselang=cs&format=json&limit=8',22000);if(!h)return null;const j=JSON.parse(h);let best:any=null,bs=0;for(const r of j.search||[]){const id=r.id;if(!id)continue;const eh=await get(`https://www.wikidata.org/wiki/Special:EntityData/${id}.json`,22000);if(!eh)continue;let e:any;try{e=JSON.parse(eh).entities?.[id]}catch{continue}const c=e?.claims?.P625?.[0]?.mainsnak?.datavalue?.value,lat=Number(c?.latitude),lon=Number(c?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<48||lat>52||lon<11||lon>20)continue;const s=score(p,r,e);if(s>bs){bs=s;best={latitude:lat,longitude:lon,wikidata_id:id,source:'Wikidata search',source_url:`https://www.wikidata.org/wiki/${id}`,confidence:s>=95?.97:s>=85?.93:.88}}}return bs>=85?best:null}catch{return null}}
async function nominatim(p:any){for(const q0 of [p.name,...variants(p.name).slice(1)]){const q=[q0,p.district,'Česko'].filter(Boolean).join(', '),h=await get('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=cz&q='+encodeURIComponent(q),22000);if(!h)continue;try{for(const x of JSON.parse(h)){const lat=Number(x.lat),lon=Number(x.lon),display=norm(x.display_name||''),typ=String(x.type||'')+' '+String(x.class||'');if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<48||lat>52||lon<11||lon>20)continue;const exact=display.includes(norm(p.name))||display.includes(norm(variants(p.name)[1]||p.name));const hist=/castle|ruins|fort|manor|palace|monastery|abbey|hrad|zricen|tvrz|zamek/i.test(typ+' '+display);if(exact&&hist)return{latitude:lat,longitude:lon,source:'OpenStreetMap Nominatim',source_url:'https://www.openstreetmap.org/',confidence:.9}}}catch{}}return null}
async function keyOk(req:Request){const{data}=await db.from('hradnik_sync_control').select('sync_key').eq('id',true).maybeSingle();const key=data?.sync_key||Deno.env.get('HRADNIK_GEOCODE_KEY')||'';if(!key)return true;return req.headers.get('x-hradnik-geocode-key')===key||req.headers.get('x-hradnik-sync-key')===key;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('',{status:204,headers:CORS});if(req.method!=='POST')return json({ok:true,service:'hradnik-geocode',version:6});if(!(await keyOk(req)))return json({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({}));const limit=Math.min(25,Math.max(1,Number(body.limit)||15));const{data:places,error}=await db.from('hradnik_places').select('id,name,kind,character,municipality,district,region,latitude,longitude,source_url,wikidata_id').eq('is_visible',true).eq('is_current',true).or('latitude.is.null,longitude.is.null').order('id').limit(limit);if(error)throw error;let updated=0,unresolved=0;const results:any[]=[];for(const p of places||[]){let gps=await findHrady(p);if(!gps)gps=await wikidataOne(p);if(!gps)gps=await nominatim(p);if(!gps){unresolved++;results.push({id:p.id,name:p.name,status:'unresolved'});continue}const now=new Date().toISOString();const{error:ue}=await db.from('hradnik_places').update({latitude:gps.latitude,longitude:gps.longitude,wikidata_id:gps.wikidata_id||p.wikidata_id||null,source_url:gps.source_url||p.source_url,last_verified_at:now,updated_at:now}).eq('id',p.id);if(ue){results.push({id:p.id,name:p.name,status:'error',error:ue.message});continue}await db.from('hradnik_place_sources').upsert({place_id:p.id,source_key:gps.source==='Wikidata search'?'wikidata_gps':gps.source==='OpenStreetMap Nominatim'?'osm_nominatim_gps':'hrady_zriceniny_gps',external_id:`${p.id}:gps:${gps.source}`,source_url:gps.source_url||null,source_label:gps.source,fetched_at:now,confidence:gps.confidence,raw_data:{latitude:gps.latitude,longitude:gps.longitude,matched_name:p.name},is_active:true},{onConflict:'place_id,source_key,external_id'});updated++;results.push({id:p.id,name:p.name,status:'updated',latitude:gps.latitude,longitude:gps.longitude,source:gps.source})}return json({ok:true,version:6,requested:limit,processed:places?.length||0,updated,unresolved,results})}catch(e){console.error(e);return json({error:String(e)},500)}})