import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import './styles.css'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://cgshssdjgzzuprlwnabl.supabase.co'
const SUPABASE_KEY = 'sb_publishable_v7jeuZC-MNUEO5nfE5xcUQ_Pu9pT-X_'
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)
const AUTH_URL = `${SUPABASE_URL}/functions/v1/hradnik-auth`
const app = document.querySelector('#app')

const TYPES = ['Vše', 'Hrad', 'Zámek', 'Zřícenina', 'Tvrz', 'Klášter', 'Opevněné místo']
const ui = { tab:'home', type:'Vše', q:'', places:[], mine:new Map(), user:null, map:null }

const esc=(s='')=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const icon=kind=>({Zřícenina:'🧱',Tvrz:'🛡️',Klášter:'⛪',Zámek:'🏯','Opevněné místo':'🏛️'}[kind]||'🏰')
const getState=id=>ui.mine.get(String(id))||{status:'none',favorite:false,rating:0,visited_on:null,note:''}
const stateLabel=s=>s==='visited'?'🟢 Navštíveno':s==='want'?'🔵 Chceme':'⚪ Nenavštíveno'

async function authApi(action,body={},token=localStorage.getItem('hradnik_session')){
 const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`
 const response=await fetch(AUTH_URL,{method:'POST',headers,body:JSON.stringify({action,...body})})
 const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Požadavek se nepodařilo dokončit.')
 return data
}
async function loadCatalog(){
 const all=[];for(let from=0;;from+=1000){const {data,error}=await supabase.from('hradnik_places').select('id,name,kind,character,district,region,municipality,latitude,longitude,description,official_url,ticket_url,opening_hours,ticket_prices,photo_urls,source_url,source_updated_at,last_verified_at').eq('is_visible',true).eq('is_current',true).order('name',{ascending:true}).range(from,from+999);if(error)throw error;all.push(...(data||[]));if(!data||data.length<1000)break}ui.places=all
}
async function loadMine(){const data=await authApi('state_list');ui.mine=new Map((data.state||[]).map(row=>[String(row.place_id),row]))}
function makeCard(place){
 const s=getState(place.id),el=document.createElement('article');el.className='place'
 el.innerHTML=`<button class="placeMain" aria-label="Otevřít ${esc(place.name)}"><span class="placeIcon">${icon(place.kind)}</span><span class="placeCopy"><b>${esc(place.name)}${s.favorite?' ⭐':''}</b><small>${esc(place.kind||'Historické místo')} · ${esc(place.district||place.region||'')}</small><small>${stateLabel(s.status)}</small></span></button><span class="quick"><button class="want" title="Chceme navštívit">🔵</button><button class="visit" title="Navštívili jsme">🟢</button></span>`
 el.querySelector('.placeMain').addEventListener('click',()=>detail(place.id));el.querySelector('.want').addEventListener('click',e=>{e.stopPropagation();setState(place.id,'want')});el.querySelector('.visit').addEventListener('click',e=>{e.stopPropagation();setState(place.id,'visited')});return el
}
function home(){
 const visited=ui.places.filter(p=>getState(p.id).status==='visited').length,wanted=ui.places.filter(p=>getState(p.id).status==='want'),favorites=ui.places.filter(p=>getState(p.id).favorite).length
 content.innerHTML=`<section class="hero"><div><p class="eyebrow">HRADNÍK</p><h1>Naše hradní výprava</h1><p class="muted">Vyber, co chcete navštívit, co už jste viděli a co si chcete zapamatovat.</p></div><div class="stats"><div><b>${visited}</b><span>navštíveno</span></div><div><b>${wanted.length}</b><span>chceme</span></div><div><b>${favorites}</b><span>oblíbené</span></div><div><b>${ui.places.length}</b><span>katalog</span></div></div></section><section><div class="sectionTitle"><h2>🔵 Chceme navštívit</h2><button id="allMine" class="linkish">Zobrazit vše</button></div><div id="homeList" class="list"></div></section>`
 const list=document.getElementById('homeList');wanted.slice(0,6).forEach(p=>list.appendChild(makeCard(p)));if(!wanted.length)list.innerHTML='<div class="empty">Zatím nic v plánu.</div>';document.getElementById('allMine').onclick=()=>{ui.tab='mine';render()}
}
function catalog(){
 content.innerHTML=`<section><div class="sectionTitle"><h1>Historická místa</h1><b id="count" class="pill"></b></div><input id="search" class="search" placeholder="Hledat název, okres nebo kraj…"><div id="chips" class="chips"></div><div id="list" class="list"></div></section>`
 const search=document.getElementById('search');search.value=ui.q;search.oninput=()=>{ui.q=search.value;renderCatalogList()};const chips=document.getElementById('chips')
 TYPES.forEach(type=>{const b=document.createElement('button');b.textContent=type;b.className=type===ui.type?'active':'';b.onclick=()=>{ui.type=type;catalog()};chips.appendChild(b)});renderCatalogList()
}
function filtered(){const q=ui.q.toLocaleLowerCase('cs-CZ').trim();return ui.places.filter(p=>(ui.type==='Vše'||p.kind===ui.type)&&`${p.name} ${p.district||''} ${p.region||''}`.toLocaleLowerCase('cs-CZ').includes(q))}
function renderCatalogList(){const list=document.getElementById('list');if(!list)return;const items=filtered();document.getElementById('count').textContent=items.length.toLocaleString('cs-CZ');list.innerHTML='';items.slice(0,1000).forEach(p=>list.appendChild(makeCard(p)));if(items.length>1000)list.insertAdjacentHTML('beforeend','<div class="empty">Použij vyhledávání pro zobrazení dalších výsledků.</div>');if(!items.length)list.innerHTML='<div class="empty">Nic nenalezeno.</div>'}
function mine(){
 content.innerHTML=`<section><h1>Naše místa</h1><div class="chips"><button id="mw">🔵 Chceme</button><button id="mv">🟢 Navštívili jsme</button><button id="mf">⭐ Oblíbené</button></div><div id="mineList" class="list"></div></section>`
 const show=mode=>{const list=document.getElementById('mineList');list.innerHTML='';const items=ui.places.filter(p=>mode==='favorite'?getState(p.id).favorite:getState(p.id).status===mode);items.forEach(p=>list.appendChild(makeCard(p)));if(!items.length)list.innerHTML='<div class="empty">Zatím prázdné.</div>'}
 mw.onclick=()=>show('want');mv.onclick=()=>show('visited');mf.onclick=()=>show('favorite');show('want')
}
function diary(){const items=ui.places.filter(p=>getState(p.id).status==='visited').sort((a,b)=>String(getState(b.id).visited_on||'').localeCompare(String(getState(a.id).visited_on||'')));content.innerHTML=`<section><h1>Naše návštěvy</h1><div id="diaryList" class="list"></div></section>`;items.forEach(p=>diaryList.appendChild(makeCard(p)));if(!items.length)diaryList.innerHTML='<div class="empty">Zatím žádné návštěvy.</div>'}
function stats(){const s={v:ui.places.filter(p=>getState(p.id).status==='visited').length,w:ui.places.filter(p=>getState(p.id).status==='want').length,f:ui.places.filter(p=>getState(p.id).favorite).length};const by={};ui.places.filter(p=>getState(p.id).status==='visited').forEach(p=>by[p.kind]=(by[p.kind]||0)+1);content.innerHTML=`<section><h1>Naše sbírka</h1><div class="stats big"><div><b>${s.v}</b><span>navštíveno</span></div><div><b>${s.w}</b><span>chceme</span></div><div><b>${s.f}</b><span>oblíbené</span></div><div><b>${ui.places.length}</b><span>katalog</span></div></div><div class="card">${Object.entries(by).map(([k,v])=>`<div class="row"><span>${icon(k)} ${esc(k)}</span><b>${v}</b></div>`).join('')||'<span class="muted">Zatím bez návštěv.</span>'}</div></section>`}
function mapView(){
 content.innerHTML='<section><h1>Mapa památek</h1><div id="map"></div></section>';ui.map?.remove();ui.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([49.8,15.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(ui.map)
 const points=ui.places.filter(p=>Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude)));points.forEach(p=>L.marker([Number(p.latitude),Number(p.longitude)],{title:p.name}).addTo(ui.map).bindPopup(`<b>${esc(p.name)}</b><br>${stateLabel(getState(p.id).status)}`));if(points.length){const bounds=L.latLngBounds(points.map(p=>[Number(p.latitude),Number(p.longitude)]));ui.map.fitBounds(bounds.pad(0.05),{maxZoom:8})};requestAnimationFrame(()=>ui.map?.invalidateSize());setTimeout(()=>ui.map?.invalidateSize(),250)
}
function render(){
 app.innerHTML=`<header><div class="wrap top"><div><div class="logo">🏰 Hradník</div><div class="sub">Hrady · zámky · zříceniny · tvrze · kláštery</div></div><div><b>${esc(ui.user?.username||'')}</b> <button id="logout">Odhlásit</button></div></div></header><main class="wrap"><nav id="nav" class="nav"></nav><div id="content"></div></main>`
 const items=[['home','🏠 Domů'],['catalog','🏰 Katalog'],['map','🗺️ Mapa'],['mine','❤️ Moje'],['diary','📖 Deník'],['stats','📊 Statistiky']];items.forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.className=ui.tab===id?'active':'';b.onclick=()=>{ui.tab=id;render()};nav.appendChild(b)});document.getElementById('logout').onclick=async()=>{try{await authApi('logout')}catch{}localStorage.removeItem('hradnik_session');localStorage.removeItem('hradnik_user');location.reload()};if(ui.tab==='home')home();if(ui.tab==='catalog')catalog();if(ui.tab==='map')mapView();if(ui.tab==='mine')mine();if(ui.tab==='diary')diary();if(ui.tab==='stats')stats()
}
async function setState(id,status){const old=getState(id),next={...old,status,visited_on:status==='visited'?(old.visited_on||new Date().toISOString().slice(0,10)):old.visited_on};const data=await authApi('state_upsert',{place_id:id,status:next.status,favorite:!!next.favorite,rating:next.rating||0,visited_on:next.visited_on||null,note:next.note||''});ui.mine.set(String(id),data.state);render()}
async function toggleFavorite(id){const old=getState(id),next={...old,favorite:!old.favorite};const data=await authApi('state_upsert',{place_id:id,status:next.status||'none',favorite:next.favorite,rating:next.rating||0,visited_on:next.visited_on||null,note:next.note||''});ui.mine.set(String(id),data.state);render()}
function detail(id){const p=ui.places.find(x=>String(x.id)===String(id));if(!p)return;const s=getState(id),o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="sheet"><button id="closeDetail" class="close">✕</button><div class="bigIcon">${icon(p.kind)}</div><p class="eyebrow">${esc(p.kind)}</p><h1>${esc(p.name)}</h1><p class="muted">${esc(p.district||'')} ${p.region?'· '+esc(p.region):''}</p><div class="actions"><button id="want" class="primary">🔵 Chceme</button><button id="visit" class="primary">🟢 Byli jsme</button><button id="fav">⭐ ${s.favorite?'Zrušit oblíbené':'Oblíbené'}</button>${p.latitude&&p.longitude?`<a class="btn" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}">📍 Navigovat</a>`:''}</div><div class="detailGrid"><div class="card"><h3>ℹ️ Informace</h3><p>${esc(p.description||'Popis zatím není ověřený.')}</p></div><div class="card"><h3>🕐 Otevírací doba</h3><p>${p.opening_hours?esc(JSON.stringify(p.opening_hours)):'Zatím neověřeno'}</p></div><div class="card"><h3>🎟️ Vstupné</h3><p>${p.ticket_prices?esc(JSON.stringify(p.ticket_prices)):'Zatím neověřeno'}</p></div><div class="card"><h3>🔗 Web</h3><p>${p.official_url?`<a target="_blank" href="${esc(p.official_url)}">Oficiální web</a>`:'Zatím není'}</p></div></div>${s.status==='visited'?`<div class="card"><h3>📖 Zápis z návštěvy</h3><input id="visitDate" type="date" value="${s.visited_on||''}"><textarea id="visitNote">${esc(s.note||'')}</textarea><button id="saveVisit" class="primary">Uložit zápis</button></div>`:''}</div>`;document.body.appendChild(o);closeDetail.onclick=()=>o.remove();want.onclick=()=>{o.remove();setState(id,'want')};visit.onclick=()=>{o.remove();setState(id,'visited')};fav.onclick=()=>{o.remove();toggleFavorite(id)};document.getElementById('saveVisit')?.addEventListener('click',async()=>{await authApi('state_upsert',{place_id:id,status:'visited',favorite:!!s.favorite,rating:s.rating||0,visited_on:visitDate.value||null,note:visitNote.value});ui.mine.set(String(id),{...s,status:'visited',visited_on:visitDate.value||null,note:visitNote.value});o.remove();render()})}
function authScreen(mode='login',error=''){app.innerHTML=`<div class="auth"><div class="authCard"><div class="logo">🏰 Hradník</div><h1>${mode==='login'?'Přihlášení':'Registrace'}</h1><p class="muted">Stačí uživatelské jméno a heslo.</p>${error?`<div class="notice">${esc(error)}</div>`:''}<form id="authForm"><label>Uživatelské jméno<input id="username" autocomplete="username" minlength="3" maxlength="32" required></label><label>Heslo<input id="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="8" required></label>${mode==='register'?'<label>Heslo znovu<input id="password2" type="password" autocomplete="new-password" minlength="8" required></label>':''}<button class="primary wide" type="submit">${mode==='login'?'Přihlásit':'Vytvořit účet'}</button></form><button id="switchAuth" class="linkish">${mode==='login'?'Nemám účet – registrace':'Už mám účet – přihlášení'}</button></div></div>`;const switchAuth=document.getElementById('switchAuth'),authForm=document.getElementById('authForm');switchAuth.onclick=()=>authScreen(mode==='login'?'register':'login');authForm.onsubmit=async e=>{e.preventDefault();const username=document.getElementById('username').value.trim(),password=document.getElementById('password').value;if(mode==='register'&&password!==document.getElementById('password2').value)return authScreen('register','Hesla se neshodují.');try{const data=await authApi(mode,{username,password},null);localStorage.setItem('hradnik_session',data.session.token);localStorage.setItem('hradnik_user',JSON.stringify(data.user));await boot()}catch(err){authScreen(mode,err.message)}}}
async function boot(){const token=localStorage.getItem('hradnik_session');if(!token)return authScreen();try{const me=await authApi('session',{},token);ui.user=me.user;await Promise.all([loadCatalog(),loadMine()]);render()}catch(err){localStorage.removeItem('hradnik_session');localStorage.removeItem('hradnik_user');authScreen('login','Relace vypršela. Přihlas se znovu.')}}
boot()
