import 'leaflet/dist/leaflet.css'
import './styles.css'
import { supabase } from './lib/supabase.js'

const app=document.querySelector('#app')
const types=['Vše','Hrad','Zámek','Zřícenina','Tvrz','Klášter','Opevněné místo']
const st={tab:'home',type:'Vše',q:'',places:[],mine:new Map(),household:null,user:null,map:null}
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))
const ico=k=>({Zřícenina:'🧱',Tvrz:'🛡️',Klášter:'⛪',Zámek:'🏯','Opevněné místo':'🏛️'}[k]||'🏰')
const ps=id=>st.mine.get(String(id))||{status:'none',favorite:false,rating:0,visited_on:null,note:''}
const sl=s=>s==='visited'?'🟢 Navštíveno':s==='want'?'🔵 Chceme':'⚪ Nenavštíveno'

async function init(){
 const {data:{session}}=await supabase.auth.getSession();st.user=session?.user||null
 if(!st.user)return login()
 const {data:member,error:e}=await supabase.from('household_members').select('household_id,display_name').eq('user_id',st.user.id).eq('status','active').limit(1).maybeSingle()
 if(e||!member)return login(e?.message||'Uživatel nemá aktivní domácnost.')
 st.household=member.household_id
 await Promise.all([loadPlaces(),loadMine()]);render()
}
async function loadPlaces(){
 const {data,error}=await supabase.from('hradnik_places').select('id,name,kind,district,region,municipality,latitude,longitude,description,official_url,ticket_url,opening_hours,ticket_prices,photo_urls,source_url').eq('is_visible',true).eq('is_current',true).order('name')
 if(error)throw error;st.places=data||[]
}
async function loadMine(){
 const {data,error}=await supabase.from('hradnik_place_state').select('place_id,status,favorite,rating,visited_on,note').eq('household_id',st.household)
 if(error)throw error;st.mine=new Map((data||[]).map(x=>[String(x.place_id),x]))
}
function card(p){
 const s=ps(p.id),el=document.createElement('article');el.className='place'
 el.innerHTML=`<button class="placeMain"><span class="placeIcon">${ico(p.kind)}</span><span class="placeCopy"><b>${esc(p.name)}${s.favorite?' ⭐':''}</b><small>${esc(p.kind)} · ${esc(p.district||p.region||'')}</small><small>${sl(s.status)}</small></span></button><span class="quick"><button class="want">🔵</button><button class="visit">🟢</button></span>`
 el.querySelector('.placeMain').onclick=()=>detail(p.id);el.querySelector('.want').onclick=()=>saveState(p.id,{status:'want'});el.querySelector('.visit').onclick=()=>saveState(p.id,{status:'visited',visited_on:s.visited_on||new Date().toISOString().slice(0,10)});return el
}
function filtered(){const q=st.q.toLocaleLowerCase('cs-CZ');return st.places.filter(p=>(st.type==='Vše'||p.kind===st.type)&&(`${p.name} ${p.district||''} ${p.region||''}`).toLocaleLowerCase('cs-CZ').includes(q))}
function render(){app.innerHTML=`<header><div class="wrap top"><div><div class="logo">🏰 Hradník</div><div class="sub">Hrady · zámky · zříceniny · tvrze · kláštery</div></div><button id="logout">Odhlásit</button></div></header><main class="wrap"><nav id="nav" class="nav"></nav><div id="content"></div></main>`;['home','catalog','map','mine','diary','stats'].forEach((id,i)=>{const b=document.createElement('button');b.textContent=['🏠 Domů','🏰 Katalog','🗺️ Mapa','❤️ Moje','📖 Deník','📊 Statistiky'][i];b.className=st.tab===id?'active':'';b.onclick=()=>{st.tab=id;render()};nav.appendChild(b)});logout.onclick=()=>supabase.auth.signOut();if(st.tab==='home')home();if(st.tab==='catalog')catalog();if(st.tab==='map')mapView();if(st.tab==='mine')mine();if(st.tab==='diary')diary();if(st.tab==='stats')stats()}
function home(){const v=st.places.filter(p=>ps(p.id).status==='visited').length,w=st.places.filter(p=>ps(p.id).status==='want').length,f=st.places.filter(p=>ps(p.id).favorite).length;content.innerHTML=`<section class="hero"><div><p class="eyebrow">HRADNÍK</p><h1>Naše hradní výprava</h1><p class="muted">Katalog se aktualizuje na pozadí. V aplikaci už nic ručně nenačítáš.</p></div><div class="stats"><div><b>${v}</b><span>navštíveno</span></div><div><b>${w}</b><span>chceme</span></div><div><b>${f}</b><span>oblíbené</span></div><div><b>${st.places.length}</b><span>katalog</span></div></div></section><section><h2>🔵 Chceme navštívit</h2><div id="homeList" class="list"></div></section>`;const a=st.places.filter(p=>ps(p.id).status==='want').slice(0,6);a.forEach(p=>homeList.appendChild(card(p)));if(!a.length)homeList.innerHTML='<div class="empty">Zatím nic v plánu.</div>'}
function catalog(){content.innerHTML=`<section><div class="sectionTitle"><div><p class="eyebrow">KATALOG</p><h1>Historická místa</h1></div><b>${filtered().length}</b></div><input id="search" class="search" placeholder="Hledat název, okres nebo kraj…"><div id="chips" class="chips"></div><div id="list" class="list"></div></section>`;search.value=st.q;search.oninput=e=>{st.q=e.target.value;catalog()};types.forEach(t=>{const b=document.createElement('button');b.textContent=t;b.className=t===st.type?'active':'';b.onclick=()=>{st.type=t;catalog()};chips.appendChild(b)});filtered().slice(0,800).forEach(p=>list.appendChild(card(p)));if(!filtered().length)list.innerHTML='<div class="empty">Nic nenalezeno.</div>'}
function mine(){content.innerHTML=`<section><p class="eyebrow">MOJE</p><h1>Naše místa</h1><div class="chips"><button id="mw">🔵 Chceme</button><button id="mv">🟢 Navštívili</button><button id="mf">⭐ Oblíbené</button></div><div id="mineList" class="list"></div></section>`;const show=k=>{mineList.innerHTML='';const a=st.places.filter(p=>k==='favorite'?ps(p.id).favorite:ps(p.id).status===k);a.forEach(p=>mineList.appendChild(card(p)));if(!a.length)mineList.innerHTML='<div class="empty">Zatím prázdné.</div>'};mw.onclick=()=>show('want');mv.onclick=()=>show('visited');mf.onclick=()=>show('favorite');show('want')}
function diary(){const a=st.places.filter(p=>ps(p.id).status==='visited');content.innerHTML=`<section><p class="eyebrow">DENÍK</p><h1>Naše návštěvy</h1><div id="diaryList" class="list"></div></section>`;a.forEach(p=>diaryList.appendChild(card(p)));if(!a.length)diaryList.innerHTML='<div class="empty">Zatím žádné návštěvy.</div>'}
function stats(){const by={};st.places.filter(p=>ps(p.id).status==='visited').forEach(p=>by[p.kind]=(by[p.kind]||0)+1);content.innerHTML=`<section><p class="eyebrow">STATISTIKY</p><h1>Naše sbírka</h1><div class="card">${Object.entries(by).map(([k,v])=>`<div class="row"><span>${ico(k)} ${esc(k)}</span><b>${v}</b></div>`).join('')||'<span class="muted">Zatím bez návštěv.</span>'}</div></section>`}
function mapView(){content.innerHTML='<section><p class="eyebrow">MAPA</p><h1>Mapa památek</h1><div id="map"></div></section>';st.map?.remove();st.map=L.map('map').setView([49.8,15.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(st.map);st.places.filter(p=>p.latitude&&p.longitude).forEach(p=>L.marker([p.latitude,p.longitude]).addTo(st.map).bindPopup(`<b>${esc(p.name)}</b><br>${sl(ps(p.id).status)}`))}
async function saveState(id,patch){const old=ps(id),next={...old,...patch};const {data,error}=await supabase.from('hradnik_place_state').upsert({household_id:st.household,place_id:id,status:next.status||'none',favorite:!!next.favorite,rating:next.rating||0,visited_on:next.visited_on||null,note:next.note||''},{onConflict:'household_id,place_id'}).select().single();if(error){alert(error.message);return}st.mine.set(String(id),data);render()}
async function toggleFav(id){const old=ps(id);await saveState(id,{favorite:!old.favorite})}
function detail(id){const p=st.places.find(x=>String(x.id)===String(id));if(!p)return;const s=ps(id),o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="sheet"><button id="close" class="close">✕</button><div class="bigIcon">${ico(p.kind)}</div><p class="eyebrow">${esc(p.kind)}</p><h1>${esc(p.name)}</h1><p class="muted">${esc(p.district||'')} ${p.region?'· '+esc(p.region):''}</p><div class="actions"><button id="want" class="primary">🔵 Chceme</button><button id="visited" class="primary">🟢 Byli jsme</button><button id="fav">⭐ ${s.favorite?'Zrušit oblíbené':'Oblíbené'}</button>${p.latitude&&p.longitude?`<a class="btn" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}">📍 Navigovat</a>`:''}</div><div class="detailGrid"><div class="card"><h3>ℹ️ Informace</h3><p>${esc(p.description||'Popis bude doplněn z ověřeného zdroje.')}</p></div><div class="card"><h3>🕐 Otevírací doba</h3><p>${p.opening_hours?esc(JSON.stringify(p.opening_hours)):'Zatím neověřeno'}</p></div><div class="card"><h3>🎟️ Vstupné</h3><p>${p.ticket_prices?esc(JSON.stringify(p.ticket_prices)):'Zatím neověřeno'}</p></div><div class="card"><h3>🔗 Web</h3><p>${p.official_url?`<a target="_blank" href="${esc(p.official_url)}">Oficiální web</a>`:'Zatím není'}</p></div></div>${s.status==='visited'?`<div class="card"><h3>📖 Zápis</h3><input id="visitDate" type="date" value="${s.visited_on||''}"><textarea id="note">${esc(s.note||'')}</textarea><button id="saveNote" class="primary">Uložit</button></div>`:''}</div>`;document.body.appendChild(o);close.onclick=()=>o.remove();want.onclick=()=>{o.remove();saveState(id,{status:'want'})};visited.onclick=()=>{o.remove();saveState(id,{status:'visited',visited_on:s.visited_on||new Date().toISOString().slice(0,10)})};fav.onclick=()=>{o.remove();toggleFav(id)};saveNote?.addEventListener('click',()=>{saveState(id,{status:'visited',visited_on:visitDate.value||null,note:note.value});o.remove()})}
function login(msg=''){app.innerHTML=`<div class="login"><div class="loginCard"><div class="logo">🏰 Hradník</div><h1>Moje historická místa</h1><p class="muted">Přihlas se stejným Google účtem jako do Domácnost+.</p>${msg?`<div class="notice">${esc(msg)}</div>`:''}<button id="google" class="primary wide">Přihlásit přes Google</button></div></div>`;google.onclick=()=>supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}})}
supabase.auth.onAuthStateChange(()=>init());init()
