import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import './styles.css'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://cgshssdjgzzuprlwnabl.supabase.co'
const SUPABASE_KEY = 'sb_publishable_v7jeuZC-MNUEO5nfE5xcUQ_Pu9pT-X_'
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)
const AUTH_URL = `${SUPABASE_URL}/functions/v1/hradnik-auth`
const app = document.querySelector('#app')

const TYPES = ['Vše', 'Hrad', 'Zámek', 'Zřícenina', 'Tvrz', 'Klášter', 'Opevněné místo']
const TYPE_COLORS = { Hrad:'#d34f4f', Zámek:'#8c63d6', Zřícenina:'#c57b38', Tvrz:'#3c7ed8', Klášter:'#38a169', 'Opevněné místo':'#6b7280' }
const PRESERVATION = [['current','Dochované + zříceniny'],['ruin','Zříceniny'],['preserved','Dochované'],['extinct','Zaniklé'],['uncertain','Domnělé / terénní'],['all','Vše']]
const MAP_STATE = [['all','Všechny moje stavy'],['none','Nenavštíveno'],['want','Chceme navštívit'],['visited','Navštíveno'],['favorite','Oblíbené']]
const ui = { tab:'home', catalogType:'Vše', catalogPreservation:'current', q:'', places:[], mine:new Map(), user:null, map:null, mapType:'Vše', mapPreservation:'current', mapState:'all' }

const $=id=>document.getElementById(id)
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const icon=kind=>({Zřícenina:'🧱',Tvrz:'🛡️',Klášter:'⛪',Zámek:'🏯','Opevněné místo':'🏛️'}[kind]||'🏰')
const stateLabel=s=>s==='visited'?'🟢 Navštíveno':s==='want'?'🔵 Chceme navštívit':'⚪ Nenavštíveno'
const getState=id=>ui.mine.get(String(id))||{status:'none',favorite:false,rating:0,visited_on:null,note:''}

function preservationOf(p){
  const t=`${p.character||''} ${p.description||''}`.toLocaleLowerCase('cs-CZ')
  if(/domněl|domnĕl|hypotet|možn|sporn|terénn|pouhý val|pouze val|archeologick/.test(t))return'uncertain'
  if(/zanikl|zanikla|zaniklo|zaniklé|zbořen|zbourán|srovnán|neexistuj|zmizel|zničeno/.test(t))return'extinct'
  if(p.kind==='Zřícenina'||/zřícen|ruin|trosk|pozůstatky po|ruiny/.test(t))return'ruin'
  return'preserved'
}
const preservationLabel=v=>({current:'Dochované + zříceniny',ruin:'Zříceniny',preserved:'Dochované',extinct:'Zaniklé',uncertain:'Domnělé / terénní',all:'Vše'}[v]||'Vše')
const matchesPreservation=(p,v)=>v==='all'||(v==='current'&&(preservationOf(p)==='preserved'||preservationOf(p)==='ruin'))||preservationOf(p)===v

async function authApi(action,body={},token=localStorage.getItem('hradnik_session')){
  const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`
  const r=await fetch(AUTH_URL,{method:'POST',headers,body:JSON.stringify({action,...body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Požadavek se nepodařilo dokončit.');return d
}
async function loadCatalog(){
  const all=[];for(let from=0;;from+=1000){const {data,error}=await supabase.from('hradnik_places').select('id,name,kind,character,district,region,municipality,latitude,longitude,description,official_url,ticket_url,opening_hours,ticket_prices,photo_urls,source_url,source_updated_at,last_verified_at').eq('is_visible',true).eq('is_current',true).order('name').range(from,from+999);if(error)throw error;all.push(...(data||[]));if(!data||data.length<1000)break}ui.places=all
}
async function loadMine(){const d=await authApi('state_list');ui.mine=new Map((d.state||[]).map(r=>[String(r.place_id),r]))}

function card(p){const s=getState(p.id),el=document.createElement('article');el.className='place';el.innerHTML=`<button class="placeMain"><span class="placeIcon">${icon(p.kind)}</span><span class="placeCopy"><b>${esc(p.name)}${s.favorite?' ⭐':''}</b><small>${esc(p.kind||'Historické místo')} · ${esc(p.district||p.region||'')}</small><small>${stateLabel(s.status)} · ${esc(preservationLabel(preservationOf(p)))}</small></span></button><span class="quick"><button class="want" title="Chceme navštívit">🔵</button><button class="visit" title="Navštívili jsme">🟢</button></span>`;el.querySelector('.placeMain').onclick=()=>detail(p.id);el.querySelector('.want').onclick=e=>{e.stopPropagation();setState(p.id,'want')};el.querySelector('.visit').onclick=e=>{e.stopPropagation();setState(p.id,'visited')};return el}

function home(){const v=ui.places.filter(p=>getState(p.id).status==='visited').length,w=ui.places.filter(p=>getState(p.id).status==='want'),f=ui.places.filter(p=>getState(p.id).favorite).length;$('content').innerHTML=`<section class="hero"><div><p class="eyebrow">HRADNÍK</p><h1>Naše hradní výprava</h1><p class="muted">Katalog se aktualizuje na pozadí. Ty jen vybíráš místa, která chcete poznat a zapamatovat si.</p></div><div class="stats"><div><b>${v}</b><span>navštíveno</span></div><div><b>${w.length}</b><span>chceme</span></div><div><b>${f}</b><span>oblíbené</span></div><div><b>${ui.places.length.toLocaleString('cs-CZ')}</b><span>katalog</span></div></div></section><section><div class="sectionTitle"><h2>🔵 Chceme navštívit</h2><button id="allMine" class="linkish">Zobrazit vše</button></div><div id="homeList" class="list"></div></section>`;w.slice(0,8).forEach(p=>$('homeList').appendChild(card(p)));if(!w.length)$('homeList').innerHTML='<div class="empty">Zatím nic v plánu.</div>';$('allMine').onclick=()=>{ui.tab='mine';render()}}

function catalog(){
 $('content').innerHTML=`<section><div class="sectionTitle"><div><p class="eyebrow">KATALOG</p><h1>Historická místa</h1></div><b id="count" class="pill"></b></div><input id="search" class="search" placeholder="Hledat název, okres nebo kraj…"><div id="typeChips" class="chips"></div><div class="filterLine"><span class="muted">Dochování:</span><select id="preservation"></select></div><div id="list" class="list"></div></section>`
 $('search').value=ui.q;$('search').oninput=()=>{ui.q=$('search').value;renderCatalogList()};$('preservation').innerHTML=PRESERVATION.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('preservation').value=ui.catalogPreservation;$('preservation').onchange=()=>{ui.catalogPreservation=$('preservation').value;renderCatalogList()}
 TYPES.forEach(t=>{const b=document.createElement('button');b.textContent=t;b.className=t===ui.catalogType?'active':'';b.onclick=()=>{ui.catalogType=t;catalog()};$('typeChips').appendChild(b)});renderCatalogList()
}
function renderCatalogList(){const q=ui.q.toLocaleLowerCase('cs-CZ').trim(),a=ui.places.filter(p=>(ui.catalogType==='Vše'||p.kind===ui.catalogType)&&matchesPreservation(p,ui.catalogPreservation)&&`${p.name} ${p.district||''} ${p.region||''} ${p.municipality||''}`.toLocaleLowerCase('cs-CZ').includes(q));$('count').textContent=a.length.toLocaleString('cs-CZ');$('list').innerHTML='';a.slice(0,1000).forEach(p=>$('list').appendChild(card(p)));if(!a.length)$('list').innerHTML='<div class="empty">Nic nenalezeno.</div>';if(a.length>1000)$('list').insertAdjacentHTML('beforeend','<div class="empty">Použij vyhledávání pro zobrazení dalších výsledků.</div>')}

function mine(){ $('content').innerHTML=`<section><p class="eyebrow">MOJE</p><h1>Naše místa</h1><div class="chips"><button id="mw">🔵 Chceme</button><button id="mv">🟢 Navštívili jsme</button><button id="mf">⭐ Oblíbené</button></div><div id="mineList" class="list"></div></section>`;const show=m=>{const a=ui.places.filter(p=>m==='favorite'?getState(p.id).favorite:getState(p.id).status===m);$('mineList').innerHTML='';a.forEach(p=>$('mineList').appendChild(card(p)));if(!a.length)$('mineList').innerHTML='<div class="empty">Zatím prázdné.</div>'};$('mw').onclick=()=>show('want');$('mv').onclick=()=>show('visited');$('mf').onclick=()=>show('favorite');show('want')}
function diary(){const a=ui.places.filter(p=>getState(p.id).status==='visited').sort((x,y)=>String(getState(y.id).visited_on||'').localeCompare(String(getState(x.id).visited_on||'')));$('content').innerHTML=`<section><p class="eyebrow">DENÍK</p><h1>Naše návštěvy</h1><div id="diaryList" class="list"></div></section>`;a.forEach(p=>$('diaryList').appendChild(card(p)));if(!a.length)$('diaryList').innerHTML='<div class="empty">Zatím žádné návštěvy.</div>'}
function stats(){const v=ui.places.filter(p=>getState(p.id).status==='visited'),s={v:v.length,w:ui.places.filter(p=>getState(p.id).status==='want').length,f:ui.places.filter(p=>getState(p.id).favorite).length},by={};v.forEach(p=>by[p.kind||'Jiné']=(by[p.kind||'Jiné']||0)+1);$('content').innerHTML=`<section><p class="eyebrow">STATISTIKY</p><h1>Naše sbírka</h1><div class="stats big"><div><b>${s.v}</b><span>navštíveno</span></div><div><b>${s.w}</b><span>chceme</span></div><div><b>${s.f}</b><span>oblíbené</span></div><div><b>${ui.places.length.toLocaleString('cs-CZ')}</b><span>katalog</span></div></div><div class="card">${Object.entries(by).map(([k,n])=>`<div class="row"><span>${icon(k)} ${esc(k)}</span><b>${n}</b></div>`).join('')||'<span class="muted">Zatím bez návštěv.</span>'}</div></section>`}

function mapView(){$('content').innerHTML=`<section><div class="sectionTitle"><div><p class="eyebrow">MAPA</p><h1>Mapa památek</h1></div><span id="mapCount" class="pill"></span></div><div class="mapFilters"><div><div class="filterLabel">Typ</div><div id="mapTypes" class="chips"></div></div><div><div class="filterLabel">Dochování</div><select id="mapPreservation">${PRESERVATION.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div><div><div class="filterLabel">Můj stav</div><select id="mapState">${MAP_STATE.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div></div><div class="mapLegend"><span><i class="dot" style="background:${TYPE_COLORS.Hrad}"></i>Hrad</span><span><i class="dot" style="background:${TYPE_COLORS.Zámek}"></i>Zámek</span><span><i class="dot" style="background:${TYPE_COLORS.Zřícenina}"></i>Zřícenina</span><span><i class="dot" style="background:${TYPE_COLORS.Tvrz}"></i>Tvrz</span><span><i class="dot" style="background:${TYPE_COLORS.Klášter}"></i>Klášter</span><span><i class="ring visited"></i>Byli jsme</span><span><i class="ring want"></i>Chceme</span><span><i class="ring favorite"></i>Oblíbené</span></div><div id="map"></div></section>`;TYPES.forEach(t=>{const b=document.createElement('button');b.textContent=t;b.className=t===ui.mapType?'active':'';b.onclick=()=>{ui.mapType=t;renderMap()};$('mapTypes').appendChild(b)});$('mapPreservation').value=ui.mapPreservation;$('mapState').value=ui.mapState;$('mapPreservation').onchange=()=>{ui.mapPreservation=$('mapPreservation').value;renderMap()};$('mapState').onchange=()=>{ui.mapState=$('mapState').value;renderMap()};ui.map?.remove();ui.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([49.8,15.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(ui.map);const pts=ui.places.filter(p=>Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude))&&(ui.mapType==='Vše'||p.kind===ui.mapType)&&matchesPreservation(p,ui.mapPreservation)).filter(p=>{const s=getState(p.id);return ui.mapState==='all'||(ui.mapState==='favorite'?s.favorite:s.status===ui.mapState)});$('mapCount').textContent=`${pts.length.toLocaleString('cs-CZ')} bodů`;pts.forEach(p=>{const s=getState(p.id),fill=TYPE_COLORS[p.kind]||'#697386',ring=s.favorite?'#e4ad19':s.status==='visited'?'#25a66d':s.status==='want'?'#3e80ef':'#fff',m=L.circleMarker([Number(p.latitude),Number(p.longitude)],{radius:s.favorite?8:6.5,fillColor:fill,fillOpacity:.94,color:ring,weight:s.favorite?4.5:3,opacity:1}).addTo(ui.map);m.bindTooltip(esc(p.name),{direction:'top',offset:[0,-7]});m.on('click',()=>detail(p.id))});if(pts.length){const b=L.latLngBounds(pts.map(p=>[Number(p.latitude),Number(p.longitude)]));ui.map.fitBounds(b.pad(.04),{maxZoom:9})};requestAnimationFrame(()=>ui.map?.invalidateSize());setTimeout(()=>ui.map?.invalidateSize(),250)}
function renderMap(){mapView()}
function render(){app.innerHTML=`<header><div class="wrap top"><div><div class="logo">🏰 Hradník</div><div class="sub">Hrady · zámky · zříceniny · tvrze · kláštery</div></div><div class="account"><b>${esc(ui.user?.username||'')}</b><button id="logout">Odhlásit</button></div></div></header><main class="wrap"><nav id="nav" class="nav"></nav><div id="content"></div></main>`;[['home','🏠 Domů'],['catalog','🏰 Katalog'],['map','🗺️ Mapa'],['mine','❤️ Moje'],['diary','📖 Deník'],['stats','📊 Statistiky']].forEach(([id,l])=>{const b=document.createElement('button');b.textContent=l;b.className=ui.tab===id?'active':'';b.onclick=()=>{ui.tab=id;render()};$('nav').appendChild(b)});$('logout').onclick=async()=>{try{await authApi('logout')}catch{}localStorage.removeItem('hradnik_session');localStorage.removeItem('hradnik_user');location.reload()};if(ui.tab==='home')home();if(ui.tab==='catalog')catalog();if(ui.tab==='map')mapView();if(ui.tab==='mine')mine();if(ui.tab==='diary')diary();if(ui.tab==='stats')stats()}
async function setState(id,status){const old=getState(id),next={...old,status,visited_on:status==='visited'?(old.visited_on||new Date().toISOString().slice(0,10)):old.visited_on};try{const d=await authApi('state_upsert',{place_id:id,status:next.status,favorite:!!next.favorite,rating:next.rating||0,visited_on:next.visited_on||null,note:next.note||''});ui.mine.set(String(id),d.state);render()}catch(err){alert(err.message)}}
async function toggleFavorite(id){const old=getState(id),next={...old,favorite:!old.favorite};try{const d=await authApi('state_upsert',{place_id:id,status:next.status||'none',favorite:next.favorite,rating:next.rating||0,visited_on:next.visited_on||null,note:next.note||''});ui.mine.set(String(id),d.state);render()}catch(err){alert(err.message)}}
function detail(id){const p=ui.places.find(x=>String(x.id)===String(id));if(!p)return;const s=getState(id),o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="sheet"><button id="closeDetail" class="close">✕</button><div class="bigIcon">${icon(p.kind)}</div><p class="eyebrow">${esc(p.kind||'Historické místo')} · ${esc(preservationLabel(preservationOf(p)))}</p><h1>${esc(p.name)}</h1><p class="muted">${esc(p.district||'')} ${p.region?'· '+esc(p.region):''}</p><div class="actions"><button id="want" class="primary">🔵 Chceme</button><button id="visit" class="primary">🟢 Byli jsme</button><button id="fav">⭐ ${s.favorite?'Zrušit oblíbené':'Oblíbené'}</button>${p.latitude&&p.longitude?`<a class="btn" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}">📍 Navigovat</a>`:''}</div><div class="detailGrid"><div class="card"><h3>ℹ️ Základní informace</h3><p>${esc(p.description||'Popis zatím není ověřený.')}</p></div><div class="card"><h3>🕐 Otevírací doba</h3><p>${p.opening_hours?esc(JSON.stringify(p.opening_hours)):'Zatím neověřeno'}</p></div><div class="card"><h3>🎟️ Vstupné</h3><p>${p.ticket_prices?esc(JSON.stringify(p.ticket_prices)):'Zatím neověřeno'}</p></div><div class="card"><h3>🔗 Odkazy</h3><p>${p.official_url?`<a target="_blank" href="${esc(p.official_url)}">Oficiální web</a>`:'Oficiální web zatím není'}</p>${p.ticket_url?`<p><a target="_blank" href="${esc(p.ticket_url)}">Vstupenky</a></p>`:''}</div></div>${s.status==='visited'?`<div class="card"><h3>📖 Zápis z návštěvy</h3><input id="visitDate" type="date" value="${s.visited_on||''}"><textarea id="visitNote">${esc(s.note||'')}</textarea><button id="saveVisit" class="primary">Uložit zápis</button></div>`:''}</div>`;document.body.appendChild(o);$('closeDetail').onclick=()=>o.remove();$('want').onclick=()=>{o.remove();setState(id,'want')};$('visit').onclick=()=>{o.remove();setState(id,'visited')};$('fav').onclick=()=>{o.remove();toggleFavorite(id)};$('saveVisit')?.addEventListener('click',async()=>{try{const d=await authApi('state_upsert',{place_id:id,status:'visited',favorite:!!s.favorite,rating:s.rating||0,visited_on:$('visitDate').value||null,note:$('visitNote').value});ui.mine.set(String(id),d.state);o.remove();render()}catch(err){alert(err.message)}})}
function authScreen(mode='login',error=''){app.innerHTML=`<div class="auth"><div class="authCard"><div class="logo">🏰 Hradník</div><h1>${mode==='login'?'Přihlášení':'Registrace'}</h1><p class="muted">Stačí uživatelské jméno a heslo.</p>${error?`<div class="notice">${esc(error)}</div>`:''}<form id="authForm"><label>Uživatelské jméno<input id="username" autocomplete="username" minlength="3" maxlength="32" required></label><label>Heslo<input id="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="8" required></label>${mode==='register'?'<label>Heslo znovu<input id="password2" type="password" autocomplete="new-password" minlength="8" required></label>':''}<button class="primary wide" type="submit">${mode==='login'?'Přihlásit':'Vytvořit účet'}</button></form><button id="switchAuth" class="linkish">${mode==='login'?'Nemám účet – registrace':'Už mám účet – přihlášení'}</button></div></div>`;$('switchAuth').onclick=()=>authScreen(mode==='login'?'register':'login');$('authForm').onsubmit=async e=>{e.preventDefault();const username=$('username').value.trim(),password=$('password').value;if(mode==='register'&&password!==$('password2').value)return authScreen('register','Hesla se neshodují.');try{const d=await authApi(mode,{username,password},null);localStorage.setItem('hradnik_session',d.session.token);localStorage.setItem('hradnik_user',JSON.stringify(d.user));await boot()}catch(err){authScreen(mode,err.message)}}}
async function boot(){const token=localStorage.getItem('hradnik_session');if(!token)return authScreen();try{const me=await authApi('session',{},token);ui.user=me.user;await Promise.all([loadCatalog(),loadMine()]);render()}catch(err){localStorage.removeItem('hradnik_session');localStorage.removeItem('hradnik_user');authScreen('login','Relace vypršela. Přihlas se znovu.')}}
boot()
